# Generated by Django 3.2 on 2023-07-09 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=30)),
                ('payment_method', models.CharField(max_length=25)),
                ('card_no', models.CharField(max_length=20)),
                ('card_exp_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('cvv_no', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
        ),
    ]
