# Generated by Django 3.2 on 2023-07-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0002_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256)),
                ('comment', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'db_table': 'feedback',
            },
        ),
    ]
