# Generated by Django 4.2.3 on 2023-08-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0004_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_image', models.ImageField(blank=True, default=None, null=True, upload_to='static/images/billboards&others/')),
            ],
        ),
    ]
