# Generated by Django 4.2.3 on 2023-09-01 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0006_alter_tempimage_options_alter_tempimage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
