# Generated by Django 3.2 on 2023-12-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0010_advertisement_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'monthlyincome',
                'db_table': 'monthlyincome',
            },
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='sub_category',
            field=models.ManyToManyField(to='adminpannel.Subcategories', verbose_name='sub_category'),
        ),
    ]
