# Generated by Django 3.2 on 2023-07-08 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpannel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('quan', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_id', models.IntegerField()),
                ('userordertime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('usersessionname', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Temp_order',
                'db_table': 'tem_order',
            },
        ),
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=50)),
                ('lastname', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('first_password', models.CharField(max_length=50)),
                ('second_password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Userlogin',
                'db_table': 'userlogin',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField()),
                ('remark', models.TextField()),
                ('s_size', models.BooleanField(max_length=50)),
                ('m_size', models.BooleanField(max_length=50)),
                ('l_size', models.BooleanField(max_length=50)),
                ('xl_size', models.BooleanField(max_length=50)),
                ('xxl_size', models.BooleanField(max_length=50)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.IntegerField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='static/images/products/')),
                ('l_img', models.ImageField(blank=True, default=None, null=True, upload_to='static/images/products/')),
                ('r_img', models.ImageField(blank=True, default=None, null=True, upload_to='static/images/products/')),
                ('f_img', models.ImageField(blank=True, default=None, null=True, upload_to='static/images/products/')),
                ('catego', models.ManyToManyField(to='adminpannel.Categories', verbose_name='category')),
                ('subcatego', models.ManyToManyField(to='adminpannel.Subcategories', verbose_name='category')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'db_table': 'product',
            },
        ),
    ]
